import React from 'react';

const AppGuide = ({ navigateToTab }) => {
    
    const roadmapItems = [
        {
            title: "Stock Analysis",
            description: "Select any stock to receive an instant, institutional-grade report. The AI performs a deep dive into the stock's health and current setup.",
            benefit: "Saves you hours of research and provides a clear, data-driven verdict.",
            targetIndex: 1,
            icon: '🧠'
        },
        {
            title: "On The Radar",
            description: "This isn't just a list of 'HOLDs'. It's a curated watchlist of stocks the AI has identified as being on the verge of a breakout, along with the exact condition it's waiting for.",
            benefit: "Helps you anticipate future trades and understand the AI's patience.",
            targetIndex: 2,
            icon: '🎯'
        },
        {
            title: "Open Positions",
            description: "A real-time dashboard of all currently active 'BUY' and 'SELL' signals generated by the AI. Each position includes the entry price, target, and stop-loss.",
            benefit: "Gives you a clear view of the AI's current market exposure and active trade plans.",
            targetIndex: 3,
            icon: '📊'
        },
        {
            title: "Index Analysis",
            description: "Get a high-level strategic overview of the entire market. The AI analyzes key indices like the Nifty 50 to determine the overall market 'weather'.",
            benefit: "Ensures your trading decisions are aligned with the broader market trend.",
            targetIndex: 4,
            icon: '📈'
        },
        {
            title: "AI Track Record",
            description: "A fully transparent performance log of every trade signal the AI has ever closed. See the wins, the losses, and the overall historical performance.",
            benefit: "Provides an honest look at the strategy's long-term effectiveness.",
            targetIndex: 5,
            icon: '🏆'
        },
        {
            title: "The Rulebook",
            description: "A detailed guide to the disciplined, data-driven strategy our AI uses. We explain our core rules for trend, volume, and risk management.",
            benefit: "Builds your confidence by showing you the professional logic behind every signal.",
            targetIndex: 6,
            icon: '📜'
        }
    ];

    return (
        <div className="w-full max-w-7xl mx-auto p-4 md:p-8 animate-fadeIn">
            <div className="text-center mb-16">
                <h2 className="text-4xl font-bold text-white mb-2">Welcome to Scrybe AI</h2>
                <p className="text-lg text-gray-400 max-w-3xl mx-auto">
                    This is your interactive guide to mastering the app. Click on any section to jump directly to it.
                </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {roadmapItems.map(item => (
                    <div 
                        key={item.title} 
                        onClick={() => navigateToTab(item.targetIndex)}
                        className="flex flex-col bg-slate-900/40 border border-slate-700/60 rounded-2xl p-6 shadow-lg cursor-pointer transition-all duration-300 hover:border-blue-500/80 hover:bg-slate-800/50 hover:scale-105"
                    >
                        <div className="text-4xl mb-4">{item.icon}</div>
                        <h3 className="font-bold text-2xl text-white">{item.title}</h3>
                        <p className="text-sm text-gray-400 mt-2 flex-grow">{item.description}</p>
                        
                        {/* --- NEW, MORE DETAILED SECTION --- */}
                        <div className="mt-4 pt-4 border-t border-slate-700">
                            <p className="text-xs font-semibold text-green-400 mb-1">Why This Is Useful:</p>
                            <p className="text-sm text-green-200/80">{item.benefit}</p>
                        </div>
                        {/* ------------------------------------ */}

                        <p className="text-sm font-semibold text-blue-400 mt-4 pt-4 border-t border-slate-800">Go to Section &rarr;</p>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default AppGuide;